aira/flutter_aira

lib/src/platform_client.dart, lib/src/platform_mq.dart, lib/src/room.dart
If a service request is in the queue and the Explorer disconnects ungracefully (e.g. quits the app, closes the browser, or loses their network connection), the request will stay in the queue until an Agent picks it and flags it as a did-not-connect (DNC). This wastes Agent time and negatively impacts our DNC metrics.
With this PR, we use MQTT's [Last Will and Testament](https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/) feature to cancel the queued service request when the MQTT client is ungracefully disconnected. This required changing the lifecycle of the MQTT client. Since the LWT message is configured when the MQTT client connects to the broker, instead of connecting after signing in, we're connecting after creating a service request.
=> fix: service request is not cancelled when disconnecting ungracefully

example/lib/main.dart, lib/flutter_aira.dart, lib/src/models/feedback.dart, lib/src/platform_client.dart
This bumps the `schemaVersion` of feedback from `1` to `2`. `shareable` has been removed; instead, `requestReview` and `shareKudos` have been added to the new `AgentFeedback` class.
=> feat: feedback version 2

lib/src/room.dart
This fixes `Room.replaceStream` so that it doesn't assume that the previous stream still has valid tracks (if we start using [`Helper.switchCamera`](https://github.com/flutter-webrtc/flutter-webrtc/blob/0dad522cc7836bf233c5bc7a0caaf3d24a7c7522/lib/src/helper.dart#L44-L83), it removes the video track from the stream) and doesn't assume that the replacement track has both audio and video tracks.
=> fix: MediaStreamTrack has been disposed

lib/flutter_aira.dart, lib/src/models/credentials.dart, lib/src/models/profile.dart, lib/src/platform_client.dart
BREAKING CHANGE: `PlatformClient.loginWithPhone` and `PlatformClient.loginWithEmail` have been removed. Now, once you have a phone or email verification code, you should call  `confirmPhoneVerificationCode` or `confirmEmailVerificationCode` to exchange the verification code for `Credentials`. Then, to create a `Session`, either `loginWithCredentials` (if `Credentials.isNewUser` is `false`) or `createAccount` (if `Credentials.isNewUser` is `true`).
=> feat!: add `PlatformClient.createAccount`

example/lib/main.dart, lib/src/platform_client.dart
This adds support for a simplified login process on devices that can't receive an SMS message or email (e.g. [Envision Glasses](https://www.letsenvision.com/envision-glasses)). It works like this:
1. The Explorer logs in on a device that _can_ receive an SMS message or email.
2. The Explorer requests a verification code for the client ID that will be used by the second device by calling `PlatformClient.createClientVerificationCode`.
3. The client verification code is shared with the second device using a QR code or some other means.
4. The second device logs in with the client verification code by calling `PlatformClient.loginWithClientVerificationCode`.
=> feat: client verification codes

example/lib/main.dart, lib/src/platform_client.dart, test/flutter_aira_test.dart
BREAKING CHANGE: The `PlatformClientConfig` constructor now uses named parameters instead of positional parameters to make it easier to add configuration options in the future.
The `X-Device-Id` header is used by Platform for fraud prevention and more, so it's important that we have a value for it if possible. This PR allows apps to provide a device ID using the `PlatformClientConfig` in cases where the defaults ([`ANDROID_ID`](https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID) on Android and [`identifierForVendor`](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor) on iOS) are inadequate.
=> feat!: configurable device ID

lib/src/platform_mq.dart, lib/src/room.dart
This switches from MQTT [Quality of Service](https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/) (QoS) level 0 (at most once) to level 1 (at least once) for critical messages that are safe to deliver multiple times.
=> feat: use QoS level 1 for critical messages

lib/src/platform_client.dart
This adds the device ID and model to the service request `context` for requests made from iOS and Android.
On my iPhone Xs, the `model` is the generic string "iPhone", which isn't very helpful. However, at this time, we aren't making any decisions based on the specific iPhone model.
=> feat: add device ID and model to service request context

example/lib/main.dart, lib/src/room.dart
BREAKING CHANGE: Clients must now implement `RoomHandler.takePhoto`. In its simplest form, this can return a frame from the video track like this:
```dart
@override
Future<ByteBuffer> takePhoto() async {
return _localStream!.getVideoTracks()[0].captureFrame();
}
```
=> feat!: add `RoomHandler.takePhoto`

lib/src/platform_client.dart
The device context will be used for fraud detection and to qualify for new-device promotional credit minutes.
=> feat: add device context to `loginWithCredentials`

lib/src/room.dart, lib/src/sfu_connection.dart
Resolves #34.
BREAKING CHANGE: The `Room` now manages its mute states separately from the `MediaStreamTrack`s. Previously, to join a `Room` with the audio muted, you would do this before calling `Room.join`:
```dart
_localMediaStream.getAudioTracks()[0].enabled = false;
``` 
Now, you will do this:
```dart
_room.setAudioMuted(true);
```
=> feat!: simplified mutes

lib/src/messaging_client.dart
This is a workaround until https://github.com/pubnub/dart/issues/103 is fixed.
=> fix: HTTP 403 error for URLs returned by `MessagingClient.getFileUrl`

lib/src/platform_client.dart
For the second time, I got the surprise to have a request which was returning HTML instead of the json information expected.
This caused the `jsonDecode` to fail parsing the body of the response. The issue here is that we didn't get much information about the body which was causing the issue (only got 'cannot parse <html>'). As it would have been nice to see the content to the body, I've added this here.
Do you think we should allow this to go into prod? My only real reserve here is that it will display what was intended for that Explorer only in Sentry. Is it possible that we could get sensible information in those responses?
Maybe we should do this only when in dev?
=> fix: handle non-JSON responses from Platform

CHANGELOG.md, example/pubspec.lock, lib/src/messaging_client.dart, lib/src/platform_client.dart, lib/src/room.dart, pubspec.yaml
BREAKING CHANGE: `MessagingClient.sendStart` has been removed and `PlatformClient.messagingClient` is now read-only.
=> fix!: no `start` message sent when call is not started with a message or file

CHANGELOG.md, example/pubspec.lock, pubspec.yaml
Resolves this error:
> Because every version of flutter_aira from git depends on intl ^0.18.0 and every version of flutter_localizations from sdk depends on intl 0.17.0, flutter_aira from git is incompatible with flutter_localizations from sdk.
=> build(deps): downgrade `intl` from `0.18.0` to `0.17.0`

lib/src/platform_client.dart
BREAKING: we no longer accept null longitude or latitude in `getAccessOfferSites` function.
=> !fix(getAccessOfferSites): NPE when either longitude or latitude is null

CHANGELOG.md, lib/src/room.dart
While triaging an [error](https://aira-io.sentry.io/share/issue/34fe6fb73a204a1b9507e020201cad69/) in Sentry, I found that two reconnects were in progress simultaneously. Since that's never desired, we now try and limit reconnects to one at a time.
=> feat: debounce reconnects

CHANGELOG.md, lib/src/platform_client.dart
Platform uses the `Accept-Language` header to localize error messages, but the `http` package does not appear to automatically set it on mobile.
=> fix: `Accept-Language` header not set on mobile

CHANGELOG.md, example/ios/Podfile.lock, example/macos/Flutter/GeneratedPluginRegistrant.swift, example/pubspec.lock, example/windows/flutter/generated_plugin_registrant.cc, example/windows/flutter/generated_plugins.cmake, lib/src/room.dart, lib/src/sfu_connection.dart, pubspec.yaml
When a user walks outside of a wifi, the application used to lose connectivity with the agent... without letting the Explorer know anything about the issue. This PR:
lets the user know when a connection is lost (not switching here, but simply lost)
without adding a reconnect button, this PR automatically attempts to reconnect as soon as a connection change happens while keeping the user aware of that pending reconnection.
uses a much more reliable reconnection process than a simple "legacy" reconnect. (we use a WebRTC restartIce).
adds a mechanism to lets the user know when a reconnection failed (This information wasn't getting back to the Explorer before)... although we still have to improve that "legacy" reconnection process which not only fails often, but doesn't provide much feedback.
=> feat: adds fallback procedure when data connection changes or is lost

CHANGELOG.md, lib/src/messaging_client.dart, pubspec.yaml
Once we have a disconnection due to network glitch or network change, PubNub wasn't attempting to reconnect. This PR fixes this.
> Based on https://www.pubnub.com/docs/sdks/dart/api-reference/publish-and-subscribe#description-2, it sounds like if the PubNub client gets disconnected from a channel for whatever reason, it won’t automatically reconnect. If we want it to do that, we need to specify a RetryPolicy when creating the client, similar to https://github.com/pubnub/dart/issues/19#issuecomment-692153308.
=> fix(PubNub): fixed pubnub reconnection issue

CHANGELOG.md, example/pubspec.lock, lib/src/models/position.dart, lib/src/platform_client.dart, pubspec.yaml
We can't base the throttling on the Position Timestamp because this timestamp can be erroneous.
=> fix(inquireForGPSActivatedOffer): location throttling was not doing what was intended

CHANGELOG.md, example/pubspec.lock, lib/src/room.dart, pubspec.yaml
All API function related with AccessOffers do filter the handled Access Offer Types, except for that call event channel...
This fix aims at fixing https://aira-io.sentry.io/issues/4175936089/events/937c99992af54a7fb95e382a82bff87e/
=> fix(call event channel): fixed the call event trigger channel by filtering AccessOfferTypes

CHANGELOG.md, example/android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, lib/src/room.dart, pubspec.yaml, test/flutter_aira_test.dart
When `Room._reconnect` was called during a presentation, the presentation stream wasn't reestablished. This is now reestablished if we were presenting.
=> fix(reconnect): reestablishment of presentation video track when a reconnect happens

CHANGELOG.md, example/pubspec.lock, example/pubspec.yaml, lib/src/platform_client.dart, lib/src/room.dart, pubspec.yaml
We have two APIs to update Explorer's locations: 
1. `Room.updateLocation` which uses a rabbitMQ API to communicate the update. This function is used to update location during a call.
2. `PlatformClient.inquireForGPSActivatedOffer` which uses a REST endpoint to know if there is a new GPS activated offer at a specific location. This function is used before calls and in the background.
These CPU intensive calls execute the same code on the backend which can cause a "endpoint modified concurrently" PlatformLocalizedException if a user ends up to execute this code while his previous call is not finished.
This PR fixes this issue by using a common throttling mechanism between these two functions and by increasing the delay between the possible calls from 1 second to 1.5 seconds.
=> fix(platform_client & room): use of a common location throttling mechanism to avoid concurrent updates

CHANGELOG.md, example/pubspec.lock, lib/src/room.dart, lib/src/sfu_connection.dart, pubspec.yaml
As reported in some of the following links:
https://airasproductt-hqa4190.slack.com/archives/C044B4WAK1U/p1689980551973879?thread_ts=1689976009.201869&cid=C044B4WAK1U
https://airasproductt-hqa4190.slack.com/archives/C044B4WAK1U/p1690404970446239
https://airasproductt-hqa4190.slack.com/archives/C044B4WAK1U/p1690417428049009
The problem:
Starting or stoping a presentation could cause a pixelation of the video on the Agent side. 
Observations:
After some experimentation, I discovered that, once I succeed to start a presentation which was causing the pixelation, the video dimensions failed to change although it should have. This "resolution" change seems to be at the source of the problem.
We also noted that a reconnect always seems to fix the issue.
The fix:
After attempting to address the …
=> fix(room): fixed the source of the video pixelation when starting or stoping a presentation

lib/flutter_aira.dart, lib/src/platform_client.dart, lib/src/platform_exceptions.dart
This exception is thrown by Platform when an operation requires the user to log in with their business credentials. The name of the required Auth0 enterprise connection is available in the `connection` property.
=> feat: add `PlatformBusinessLoginRequiredException`

CHANGELOG.md, lib/flutter_aira.dart, lib/src/platform_client.dart, lib/src/platform_exceptions.dart, lib/src/room.dart, pubspec.yaml
`PlatformClient.deleteAccount` is now capable to throw `PlatformDeleteAccountException` to indicate the failure reason.
=> feat: new Exception to indicate account deletion failure reasons

CHANGELOG.md, example/pubspec.lock, lib/src/models/user.dart, pubspec.yaml
We are adding a user property `aiDailyMessageLimit` that will determine how many AI image description requests an Explorer can make per day.
=> feat: add `User.aiDailyMessageLimit`

CHANGELOG.md, example/pubspec.lock, lib/src/room.dart, lib/src/sfu_connection.dart, pubspec.yaml
This PR addresses the issue described [here](https://aira.slack.com/archives/C01LB57N74Z/p1706390196107819).
Here is the flow of events as a call start in a very simple form:
1. Client: Room.createServiceRequest is called.
2. Room: The service status request is both received from a RabbitMQ message and polled
3. Room: We get the Request ServiceRequest status and do nothing
4. Room: We get the Assigned ServiceRequest status and notify listeners. Step 5 & 6 happen concurrently.
5. Client: We create the video track and join the room (which is creating the video transceiver)
6. Room: Continues the connection process.
7. Room: We get the Started ServiceRequest status and update the ParticipantStatus and notify listeners.
Things to keep in mind as you continue this reading:
A) …
=> fix: fixed issue where calls could start without video

CHANGELOG.md, example/pubspec.lock, pubspec.yaml
Flutter 3.19.0 and 3.19.1 were causing issues with project EARTH.
=> build(deps): downgraded flutter to 3.16.9

CHANGELOG.md, example/pubspec.lock, lib/src/platform_mq.dart, pubspec.yaml
Our effort to keep RabbitMQ up to date brought an incompatibility issue: 
> Maybe in the rabbitmq_web_mqtt v3.12.13 plugin there was a change on how incoming connections are handled
This PR changes that protocol and was tested with both the new version of RabbitMQ and the previous one to ensure backward compatibility
=> chore: updated MQTT's WebSocket protocol for better support of newer RabbitMQ versions.

CHANGELOG.md, example/pubspec.lock, lib/src/models/chat/agent_feedback_info.dart, pubspec.yaml
This PR 
1. Updates the enum class `AgentFeedbackState` to include the new state `AgentFeedbackState.assigned`
2. Replaces `AgentFeedbackState.inProgress` with `AgentFeedbackState.started`
Full list can be found [here](https://github.com/aira/aira-backend-services/blob/main/api-models/src/main/resources/openapi/task-manager.yaml#L693-L697)
=> Update the enum class [AgentFeedbackState]

CHANGELOG.md, example/pubspec.lock, lib/flutter_aira.dart, lib/src/models/account.dart, pubspec.yaml
Added a new accessAi property to the User's Account (Profile) data.
**Details**
Introduced the accessAi property to the User's Account (Profile) model.
This property is intended to manage Access AI permissions to different user's profiles.
**Example**:
A response example including the new `accessAi` property can be found in the following [issue](https://linear.app/airaio/issue/PLAT-269/limit-access-ai-platform-add-support-for-explorer-app#comment-b851829b).
=> Limit access ai

CHANGELOG.md, example/lib/main.dart, example/pubspec.yaml, lib/src/extension/string_extension.dart, lib/src/models/track.dart, lib/src/platform_client.dart, lib/src/room.dart, pubspec.yaml
This adds feature to manage multiple agents tracks while doing Transfer call, including:
- Adds agents track to memory by agentId while agent joins.
- Removes the agent track when an agent leaves the call.
This makes Explorer or ASL app to have control over tracks. resulting in less memory usage than before as well as switching between agents video track when an agent leaves during the transfer call.
=> Multiple agent support

lib/src/models/feedback.dart, pubspec.yaml
This pull request adds a new `disappointed` rating to the `Rating` enum and introduces a utility method to map ratings to a yes/no value. The changes also update the package version to `3.3.2`.
**Feedback rating enhancements:**
* Added a new `disappointed` value to the `Rating` enum, representing a stronger negative sentiment.
* Updated the `fromValue` static method in `Rating` to support the new `disappointed` value.
* Added a `toYesNo()` method to the `Feedback` class to map `excellent` ratings to `true`, `disappointed` ratings to `false`, and other ratings to `null`.
**Version update:**
* Bumped the package version from `3.2.2` to `3.3.2` in `pubspec.yaml`.
=> Add Feedback rating option
