aira/flutter_aira

lib/src/platform_client.dart, lib/src/room.dart
This handles the `PHOTO` participant event by uploading a frame from the video track.
**This is a temporary solution.** Eventually, we will call a method on the `RoomHandler` (`takePhoto`?) and let the app determine how to take the photo.
=> feat: low-res photo support

example/lib/main.dart, example/pubspec.lock, lib/flutter_aira.dart, lib/src/messaging_client.dart, lib/src/models/sent_file_info.dart, lib/src/platform_client.dart, lib/src/room.dart, pubspec.yaml
Here I have separated the Messaging from WebRTC's room as they are not related. This makes it much easier to send message before calling.
=> feat: start call with message and file

lib/src/messaging_client.dart, lib/src/platform_client.dart
https://www.pubnub.com/docs/resources/migration-guides/pam-v3-migration#differences-between-v2-and-v3
=> feat(messaging): migrate from PubNub Access Manager v2 to v3

lib/src/room.dart
BREAKING CHANGE: Removes the deprecated methods `Room.messageStream` and `Room.sendMessage`.
=> feat!: remove deprecated messaging methods from `Room`

CHANGELOG.md, example/pubspec.lock, pubspec.yaml
0.0.30 - 2022-11-17
Added
- `User.languages` and `User.cloneWith` (#54)
- `PlatformClient.updateName`, `PlatformClient.updatePreferredLanguages`, 
`PlatformClient.verifyEmailUpdate`, `PlatformClient.verifyPhoneNumberUpdate` and 
`PlatformClient.confirmPhoneNumberUpdate` (#54).
=> release 0.0.30

lib/flutter_aira.dart, lib/src/models/access_offer.dart, lib/src/models/call_history.dart, lib/src/models/convertion_extension.dart, lib/src/models/usage.dart, lib/src/platform_client.dart
adding API for Access Offers.
Will add the API to send position updates...
=> feat: adding API for Access Offers

CHANGELOG.md, example/ios/Podfile.lock, example/linux/flutter/generated_plugin_registrant.cc, example/linux/flutter/generated_plugins.cmake, example/pubspec.lock, pubspec.yaml
- added Access Offer API
- updated example's pubspec and pod
=> build: release 0.0.32

CHANGELOG.md, example/.gitignore, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner/Info.plist, example/lib/main.dart, example/macos/Flutter/GeneratedPluginRegistrant.swift, example/pubspec.lock, lib/src/platform_client.dart, pubspec.yaml
Plus updates for [Flutter 3.7.0](https://medium.com/flutter/whats-new-in-flutter-3-7-38cbea71133c)!
=> build: bump dependencies

CHANGELOG.md, example/pubspec.lock, lib/flutter_aira.dart, lib/src/models/minute_sharing.dart, lib/src/models/usage.dart, lib/src/platform_client.dart, pubspec.yaml
Adds all the endpoints required to handle the Minute Sharing Page.
=> feat: minute sharing

CHANGELOG.md, example/pubspec.lock, lib/flutter_aira.dart, lib/src/models/user.dart, lib/src/platform_client.dart, pubspec.yaml
3 new functions to handle Lyft account linking: getLyftAuthorizationUrl, sendLyftAuthorizationCode and revokeLyftAuthorization
=> feat: added rideshare api

CHANGELOG.md, example/ios/Podfile.lock, example/macos/Flutter/GeneratedPluginRegistrant.swift, example/pubspec.lock, lib/src/room.dart, pubspec.yaml
If we were in a queue and the Explorer was requesting a camera switch, the application would crash.
=> fix: prevented a room camera switch while we are in queue

CHANGELOG.md, example/pubspec.lock, lib/src/models/convertion_extension.dart, lib/src/models/position.dart, lib/src/platform_client.dart, lib/src/room.dart, pubspec.yaml
- Added Equitable to help perform deep equality within objects
- Added Rest Endpoint access to /user/location for an easy access to available Site offer
- Added Functions to Position object to help manage Site offers and requests
=> feat(PlatformClient): New API to retrieve available Free Site Access.

CHANGELOG.md, lib/src/room.dart, pubspec.yaml
fixed the duration per call limit where unlimited is not only represented by null but by -1 also
=> fix(onAccessOfferChange): the remainingTime is now set as unlimited when duration_per_call is -1 as well.

CHANGELOG.md, example/pubspec.lock, lib/src/models/position.dart, lib/src/room.dart, pubspec.yaml
- added `Position.toJson` and `Position.fromJson` (#82)
- added `Position.speedFrom` to be able to calculate speed between two coordinates using timestamps (#82)
=> feat(Position): added utility functions around Position

CHANGELOG.md, example/ios/Podfile.lock, example/pubspec.lock, lib/src/models/feedback.dart, pubspec.yaml
*** BREAKING ***  The `Rating` enum used for feedback now has one more rating possibility: "Excellent".
=> feat(Rating): added excellent rating

CHANGELOG.md, example/pubspec.lock, lib/src/models/call_history.dart, lib/src/platform_client.dart, pubspec.yaml
Simple version updates to take new lint rules into consideration and ensure our app is taking advantage of all new bug fixes.
=> build(deps): bumping plugin versions

lib/src/models/user.dart, lib/src/platform_client.dart
This pull request adds the ability to accept the privacy policy thru the API.
=> feat: Addition of terms of service

lib/src/platform_client.dart
Simple use of rest delete on the right endpoint.
=> feat: added endpoint to delete account

CHANGELOG.md, example/pubspec.lock, lib/src/models/chat/agent_feedback_info.dart, pubspec.yaml
Rename `authorFullName` to `authorFirstName`
=> Update agent name

CHANGELOG.md, lib/src/room.dart, pubspec.yaml
Handle Left event triggered when there is a call transfer and Agent 1 leaves the call
=> Left event support and change default in ServiceRequestState

CHANGELOG.md, example/macos/Flutter/GeneratedPluginRegistrant.swift, example/pubspec.lock, example/pubspec.yaml, example/web/index.html, lib/src/room.dart, pubspec.yaml
This PR updates libraries required to use with flutter 3.22.1
=> Updated libraries required to use with flutter 3.22.1

CHANGELOG.md, example/pubspec.lock, lib/src/platform_client.dart, pubspec.yaml
Exposing the following two constants.
- `PlatformClient.kEmailVerification` 
- `PlatformClient.kPhoneVerification`
=> Add kEmailVerification and kPhoneVerification in PlatformClient

CHANGELOG.md, example/pubspec.lock, lib/flutter_aira.dart, lib/src/enum/user_property.dart, lib/src/models/callHistory/build_ai.dart, lib/src/models/callHistory/call_history.dart, lib/src/platform_client.dart, pubspec.yaml
This PR includes the following updates:
- Add buildAiProgramJoined: Introduced a new user property for buildAI.
- Get Call History for a Single Call: Implemented the getCallHistorySingleCall API call.
- Update Session Share Status: Integrated the updateSessionShareStatus API call into the flow.
=> BuildAI calls

CHANGELOG.md, example/pubspec.lock, lib/src/platform_client.dart, pubspec.yaml
Add chatRoomId in `createServiceRequest`
=> Add chatRoomId in `createServiceRequest`

CHANGELOG.md, example/pubspec.lock, lib/flutter_aira.dart, lib/src/models/access_offer.dart, lib/src/platform_client.dart, pubspec.yaml
New field `buildAiAvailable ` was added to the AccessOfferDetails
=> Access offer details build ai field

CHANGELOG.md, example/pubspec.lock, lib/src/models/callHistory/call_history.dart, lib/src/platform_client.dart, pubspec.yaml
* Make `endTimeStamp` nullable in `CallSession`
=> Make `endTimeStamp` nullable in `CallSession`

CHANGELOG.md, example/pubspec.lock, lib/src/models/callHistory/build_ai.dart, pubspec.yaml
Add `copyWith` function to `BuildAi` class
=> Add `copyWith` function to `BuildAi` class

CHANGELOG.md, example/pubspec.lock, lib/src/models/callHistory/build_ai.dart, pubspec.yaml
* Add new Build AI status `ineligibleCallTransfer` that corresponds to `INELIGIBLE_CALL_TRANSFER` in the platform.
=> Add new build ai status `ineligibleCallTransfer`

CHANGELOG.md, lib/src/models/user.dart, pubspec.yaml
This only adds isASL property to user model
=> add ASL property to user

CHANGELOG.md, lib/src/platform_client.dart, lib/src/room.dart, pubspec.yaml
This adds client_id field to gps data that is pushing to the mqtt channel
=> Add ClientId to gps data while in a call

CHANGELOG.md, example/pubspec.lock, lib/src/enum/user_property.dart, lib/src/models/user.dart, pubspec.yaml
- Add new properties `googleEmail` and `appleEmail` to User.
- Refactor and add missing properties `buildAiProgramJoined` and `showReferrerRewardSplash` to User
=> Refactor and add new properties to User

CHANGELOG.md, example/pubspec.lock, lib/flutter_aira.dart, lib/src/models/account.dart, pubspec.yaml
AccessAI user property was renamed and updated
=> Access ai individual restrictions

example/pubspec.lock, lib/src/platform_client.dart, pubspec.yaml
- Adds `fullName` and `lastName` to **createAccount**
=> Add `fullName` and `lastName`

CHANGELOG.md, lib/src/platform_client.dart, pubspec.yaml
Add FCM token registration API
=> Feature/register FCM token api

CHANGELOG.md, example/pubspec.lock, lib/src/enum/user_property.dart, lib/src/models/user.dart, lib/src/platform_client.dart, pubspec.yaml
- A new hasMetaGlasses user property was added to enable calls with Meta Ray-Ban glasses.
- The ServiceRequest has also been updated to include intents (Call Purposes).
=> Add hasMetaGlasses UserProperty

CHANGELOG.md, lib/src/platform_client.dart, lib/src/platform_mq.dart, pubspec.yaml
- This adds staging environment as well as corresponding api addresses to `PlatformClient` and `PlatformMQ`
=> Add staging environment

CHANGELOG.md, example/pubspec.lock, lib/src/room.dart, pubspec.yaml
Adds `isCameraFocusCentered` to the `Room` model to get data from the dashboard, indicating whether the agent requested centered focus while taking the picture."
=> Set centerFocus

lib/src/models/profile.dart
=> add ASL language

pubspec.yaml
=> Increase version

CHANGELOG.md, example/pubspec.lock, lib/src/models/service_request.dart, lib/src/platform_client.dart, lib/src/room.dart, pubspec.yaml
- Updated Platform Client to include SensorData APIs.
- Added a new field to the ServiceRequest API.
=> Add Sensor Date Collector API

CHANGELOG.md, example/pubspec.lock, lib/src/models/service_request.dart, lib/src/room.dart, pubspec.yaml
A new field, `ringback`, has been added to the `service-request` response.
=> Add ringback to the service_request.dart

.github/actions/install_dependencies/action.yml, .github/workflows/ci_workflow.yml, CHANGELOG.md, README.md, example/pubspec.lock, lib/src/models/service_request.dart, pubspec.yaml
- This PR adds a GitHub Actions workflow to automate pull request validation.
- Removes Bitrise Badge
=> Add Github Actions CI 

CHANGELOG.md, lib/src/platform_client.dart, pubspec.yaml
This adds new method `uploadPhotoWithUint8List`
=> Upload photo with Uint8List

CHANGELOG.md, example/pubspec.lock, lib/src/platform_client.dart, pubspec.yaml
- Add new verification constant `kDeviceKeyVerification` with value `DEVICE_KEY`
=> Add new verification constant `kDeviceKeyVerification` 

CHANGELOG.md, example/pubspec.lock, lib/src/platform_client.dart, pubspec.yaml
**BREAKING:**
- Rename `kEmailVerification` to `kEmailAuthProviderId`
- Rename `kPhoneVerification` to `kPhoneAuthProviderId`
- Rename `kDeviceKeyVerification` to `kMdmAuthProviderId` and change its value to `LOGIN_TOKEN`
=> Rename to auth provider Id

CHANGELOG.md, example/ios/Podfile.lock, example/ios/Runner/AppDelegate.swift, example/pubspec.lock, example/pubspec.yaml, lib/src/models/service_request.dart, pubspec.yaml
Expose the `serviceUuid` from the `ServiceRequest`.
=> Feature/expose service UUID

CHANGELOG.md, lib/src/room.dart, pubspec.yaml
=> Fix _mq has not been initialized error

CHANGELOG.md, example/pubspec.lock, lib/src/models/user.dart, pubspec.yaml
=> Expose uuid from User

lib/src/models/access_offer.dart, pubspec.yaml
- makes a property nullable at json parsing level
=> Alabama support

pubspec.yaml
This pull request makes a minor update to the SDK version in the `pubspec.yaml` file, rolling back the version from 3.3.2 to 3.3.0.
=> upgrade to 3.3.0
